### ISSUE TITLE
assert output/expect not working

### ISSUE THREAD

**Issue by ThePeach** [oddbird/true#115]
Hello and thank you for this wonderful tool.

I currently have the following in one of my test suite:

```
@import '../node_modules/sass-true/sass/true';
@import '../sass/gravy';
//...
@include describe('Initialisation') {
//...
  @include it('Checks gravy-font outputs the right information') {
    @include assert {
      @include output {
        @include gravy-font('primary');
      }

      @include expect {
        font-family: "Arial", sans-serif;
        font-weight: "regular";
      }
    }
  }
}
```

Whatever I write in the `output` or `expect` nothing changes and it always gives a passed test.
No idea what's wrong.

**Comment by mirisuzanne** [comment]
Are you using the mocha integration to compile tests, or are you doing a simple sass compile? Can you show me the output you get when the test should be failing?

**Comment by ThePeach** [comment]
Yeah, I'm using mocha.

```
    @include assert('gravy-fonts works') {
      @include output() {
        @include gravy-font('primary');
      }

      @include expect() {
        font-family: "this is wrong!";
        font-weight: "irregular";
      }
    }
```

output
```
$ npm test

> @buildit/gravy@2.0.0-alpha.2 test /Users/peach/repos/gravy
> mocha

/Users/peach/repos/gravy/node_modules/sass-true/sass/true/_messages.scss:34 DEBUG: 4 Tests, 2 Passed, 0 Failed, 2 Output to CSS
/Users/peach/repos/gravy/node_modules/sass-true/sass/true/_messages.scss:34 DEBUG: 1 Module, 4 Tests, 11 Assertions


  Initialisation
    ✓ Checks the initialisation creates all the needed global vars


  1 passing (5ms)
```

**Comment by ThePeach** [comment]
You can see the whole test file here:  https://github.com/buildit/gravy/blob/2.0/test/init.scss

**Comment by mirisuzanne** [comment]
Well, that's very strange. It looks like Sass is giving the proper result: `4 Tests, 2 Passed, 0 Failed, 2 Output to CSS` (Sass can't compare output blocks). But the Mocha parser is failing to get past the first test. 

@jgerigmeyer Can you take a look at this? I'm able to reproduce this locally, after cloning https://github.com/buildit/gravy/ and running `npm install; npm test` on the `2.0` branch.

**Comment by jgerigmeyer** [comment]
@ThePeach @mirisuzanne It fails because the `@include gravy-init;` is inside an `it() {` block. The tests run fine if `@include gravy-init;` is moved out to the top of the file.

I'm not very familiar with True's syntax... are assertions the only things expected within an `it() {` block?

**Comment by mirisuzanne** [comment]
Aha - not exactly, but the Mocha CSS parser does break on unexpected CSS-output inside a test block. If `gravy-init` creates output CSS, that's likely the issue.

**Comment by jgerigmeyer** [comment]
👍  (Is that documented in the True docs? If so, I wasn't able to find it easily...)

**Comment by ThePeach** [comment]
ok, just tested myself and yeah, moving `gravy-init` to the outside of the `describe` will make the tests fail/pass as intended. 
Now what's not clear to me is what's going on here: is the output of the mixin captured? the mixin I'm calling later on `gravy-font` depends on some variables initialised by `gravy-init`. I'm a bit confused.

**Comment by mirisuzanne** [comment]
True works in several steps:

1. First the Sass is compiled into CSS, with comments that show the test structure. This step works with or without Mocha. The resulting CSS looks something like this (showing a passing test, a failing test, and one output test):

```css
/* # Module: Utilities */
/* ------------------- */
/* Test: Map Add [function] */
/*   ✔ Returns the sum of two numeric maps */
/* */
/* Test: Simple assertions */
/*   ✖ FAILED: [assert-true] True should assert true. */
/*     - Output: [bool] false */
/*     - Expected: [bool] true */
/*     - Details: Broken tautology is broken. */
/* */
/* Test: CSS output assertions */',
/*   ASSERT: Input and output selector patterns match   */
/* */
/*   OUTPUT   */
.test-output {
  -property: value; }

/*   END_OUTPUT   */
/* */
/*   EXPECTED   */
.test-output {
  -property: value; }

/*   END_EXPECTED   */
/* */
/*   END_ASSERT   */
```

2. Our Mocha integration parses that output CSS (not the Sass), and expects to see a structure that it understands. If the CSS output doesn't make sense to the parser, that might cause errors.

I'd love for @carljm to look at this - because he recently added a feature to ignore output that can't be parsed. That should take care of this problem, if we're understanding the problem right. I wonder if that's limited inside tests (needs documentation), or if this is a remaining bug (needs fixing)?

**Comment by kyleoliveiro** [comment]
I'm facing a similar issue while testing an `extends()` mixin:

```
@mixin extends($selectors...) {
  @each $selector in $selectors {
    @extend #{$selector};
  }
}
```

In my test file:

```
@include assert {
  @include output {
    .bold {
      font-weight: bold;
    }

    .component {
      @include extends('bold');
    }
  }

  @include expect {
    .bold,
    .component {
      font-weight: bold;
    }
  }
}
```

This should pass, but I get the following error:

```
AssertionError [ERR_ASSERTION]:  (".test-output .bold,
.test-output .component {
  font-weight: bold;
}" equal ".test-output .bold,
.test-output .component,
.test-output .component {
  font-weight: bold;
}")
```

**Comment by mirisuzanne** [comment]
By default, True adds a `.test-output` wrapper class - so that you can test raw property/value output, without the selector. To remove that, pass `false` as the first argument to both `output` and `expect`:

```scss
@include assert {
  @include output(false) {
    .bold {
      font-weight: bold;
    }

    .component {
      @include extends('bold');
    }
  }

  @include expect(false) {
    .bold,
    .component {
      font-weight: bold;
    }
  }
}
```
