### ISSUE TITLE
get-function and mocha integration

### ISSUE THREAD

**Issue by mighty-pirate** [oddbird/true#122]
I am getting an output issue with the mocha integration. I am sorry if this is already a known issue but I couldn't find an issue or fix for it.

If I run the tests using node-sass (4.8.3) and libsass (3.5.2), the problem does not occur but within the mocha integration, `get-function` is output as a string and any args appended to the end.

For example

```scss
@function name($arg1, $arg2) {
  @return '#{$arg1} #{$arg2}';
}

$args: ('Guybrush', 'Threepwood');
$result: call(get-function('name'), $args...);

.test {
  font-family: $result;
}
```
The output should be:

```css
.test {
  font-family: 'Guybrush Threepwood';
}
```

but is instead:

```css
.test {
  font-family: get-function('name')('Mighty', 'Pirate');
}
```
