### ISSUE TITLE
Latest version asserts more than it should

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#131]
So I've set up a reduced test case here: https://gist.github.com/chrisopedia/b8aaf55b2de9d5eb37a371c6ea55dfd6 in order to show the smallest set of mixins required to create the following output.  After upgrading to the newest version of True, my test is now failing expecting a lot more output than would be output.  Here's the test:

```scss
@import "true";
@import "../../../grid";

@include test-module("mixin: grid framework") {
	@include test("it should output styles for columns within a fluid grid framework") {
		@include assert() {
			@include output(false) {
				@include make-grid-modifiers(2, 10px, (xs: 0));
			}

			@include expect(false) {
				.col-xs-1,
				.col-xs-2 {
					position: relative;
					box-sizing: border-box;
					/* Prevent columns from collapsing when empty */
					min-height: .0625rem;
					/* Inner gutter via padding */
					padding-right: 5px;
					padding-left: 5px;
				}

				.col-xs-pull-1 {
					right: 50%;
				}

				.col-xs-pull-2 {
					right: 100%;
				}

				.col-xs-push-1 {
					left: 50%;
				}

				.col-xs-push-2 {
					left: 100%;
				}

				.col-xs-suffix-1 {
					margin-right: 50%;
				}

				.col-xs-suffix-2 {
					margin-right: 100%;
				}

				.col-xs-offset-1 {
					margin-left: 50%;
				}

				.col-xs-offset-2 {
					margin-left: 100%;
				}
			}
		}
	}
}
```

And the error:

```
      AssertionError [ERR_ASSERTION]:  (".col-xs-1,
.col-xs-2,
.col-xs-3,
.col-xs-4,
.col-xs-5,
.col-xs-6,
.col-xs-7,
.col-xs-8,
.col-xs-9,
.col-xs-10,
.col-xs-11,
.col-xs-12,
.col-sm-1,
.col-sm-2,
.col-sm-3,
.col-sm-4,
.col-sm-5,
.col-sm-6,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
.col-md-1,
.col-md-2,
.col-md-3,
.col-md-4,
.col-md-5,
.col-md-6,
.col-md-7,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
.col-lg-1,
.col-lg-2,
.col-lg-3,
.col-lg-4,
.col-lg-5,
.col-lg-6,
.col-lg-7,
.col-lg-8,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12 {
  position: relative;
  box-sizing: border-box;
  /* Prevent columns from collapsing when empty */
  min-height: .0625rem;
  /* Inner gutter via padding */
  padding-right: 5px;
  padding-left: 5px;
}

.col-xs-pull-1 {
  right: 50%;
}

.col-xs-pull-2 {
  right: 100%;
}

.col-xs-push-1 {
  left: 50%;
}

.col-xs-push-2 {
  left: 100%;
}

.col-xs-suffix-1 {
  margin-right: 50%;
}

.col-xs-suffix-2 {
  margin-right: 100%;
}

.col-xs-offset-1 {
  margin-left: 50%;
}

.col-xs-offset-2 {
  margin-left: 100%;
}" equal ".col-xs-1,
.col-xs-2 {
  position: relative;
  box-sizing: border-box;
  /* Prevent columns from collapsing when empty */
  min-height: .0625rem;
  /* Inner gutter via padding */
  padding-right: 5px;
  padding-left: 5px;
}

.col-xs-pull-1 {
  right: 50%;
}

.col-xs-pull-2 {
  right: 100%;
}

.col-xs-push-1 {
  left: 50%;
}

.col-xs-push-2 {
  left: 100%;
}

.col-xs-suffix-1 {
  margin-right: 50%;
}

.col-xs-suffix-2 {
  margin-right: 100%;
}

.col-xs-offset-1 {
  margin-left: 50%;
}

.col-xs-offset-2 {
  margin-left: 100%;
}")
      + expected - actual

       .col-xs-1,
      -.col-xs-2,
      -.col-xs-3,
      -.col-xs-4,
      -.col-xs-5,
      -.col-xs-6,
      -.col-xs-7,
      -.col-xs-8,
      -.col-xs-9,
      -.col-xs-10,
      -.col-xs-11,
      -.col-xs-12,
      -.col-sm-1,
      -.col-sm-2,
      -.col-sm-3,
      -.col-sm-4,
      -.col-sm-5,
      -.col-sm-6,
      -.col-sm-7,
      -.col-sm-8,
      -.col-sm-9,
      -.col-sm-10,
      -.col-sm-11,
      -.col-sm-12,
      -.col-md-1,
      -.col-md-2,
      -.col-md-3,
      -.col-md-4,
      -.col-md-5,
      -.col-md-6,
      -.col-md-7,
      -.col-md-8,
      -.col-md-9,
      -.col-md-10,
      -.col-md-11,
      -.col-md-12,
      -.col-lg-1,
      -.col-lg-2,
      -.col-lg-3,
      -.col-lg-4,
      -.col-lg-5,
      -.col-lg-6,
      -.col-lg-7,
      -.col-lg-8,
      -.col-lg-9,
      -.col-lg-10,
      -.col-lg-11,
      -.col-lg-12,
      -.col-xl-1,
      -.col-xl-2,
      -.col-xl-3,
      -.col-xl-4,
      -.col-xl-5,
      -.col-xl-6,
      -.col-xl-7,
      -.col-xl-8,
      -.col-xl-9,
      -.col-xl-10,
      -.col-xl-11,
      -.col-xl-12 {
      +.col-xs-2 {
         position: relative;
         box-sizing: border-box;
         /* Prevent columns from collapsing when empty */
         min-height: .0625rem;```
