### ISSUE TITLE
How can we test a placeholder?

### ISSUE THREAD

**Issue by pattisahusiwa** [oddbird/true#151]
````
Dependencies:
  - mocha: 6.2.0
  - sass-true: 5.0.0
````

Consider this code.
```scss
@mixin use-mixin {
  font-size: 2rem;
  line-height: 3rem;
}

%use-placeholder {
  font-size: 2rem;
  line-height: 3rem;
}

@mixin mixin-use-placeholder {
  @extend %use-placeholder;
}

.mixin {
  @include use-mixin();
}

.placeholder {
  @extend %use-placeholder;
}

.mixin-placeholder {
  @include mixin-use-placeholder();
}
````

How can we test it? Only `use-mixin` is passed.
````scss
@include describe("Able to test placeholder") {
  @include it("Use mixin") {
    @include assert {
      @include output {
        @include use-mixin;
      }

      @include expect {
        font-size: 2rem;
        line-height: 3rem;
      }
    }
  }

  @include it("Use placeholder") {
    @include assert {
      @include output {
        @extend %use-placeholder;
      }

      @include expect {
        font-size: 2rem;
        line-height: 3rem;
      }
    }
  }

  @include it("Use mixin-placeholder") {
    @include assert {
      @include output {
        @include mixin-use-placeholder;
      }

      @include expect {
        font-size: 2rem;
        line-height: 3rem;
      }
    }
  }
}
````

Thank you.
