### ISSUE TITLE
"Can't find stylesheet to import" error with sass, and no problem with node-sass

### ISSUE THREAD

**Issue by maximelebreton** [oddbird/true#165]
Hello, and first of all, thanks for this library!

I have this structure based on `parcel`, `sass` and `jest`:
```
/__tests__
  test.scss
  test__sass.js
/node_modules
  /sassdash
/src
  /scss
    styles.scss
```

And in `styles.scss`, some @functions are using `sassdash`, and everything works as excepted.

**src/styles.scss**
```scss
@import "../../node_modules/sassdash";

@function my-function($value) {
  @return _encode("Hello " + $value");
}
```

**test.scss**
```scss
$true-terminal-output: true;
@import "true";
@import "../../src/styles";

@include describe('test describe') {
    @include it('test it') {
        @include assert-equal(my-function('world'), "Hello%20world");
    }
}
```

**test__sass.js**
```js
var path = require('path');
var sassTrue = require('sass-true');

var sassFile = path.join(__dirname, 'test.scss');

sassTrue.runSass(
  {
    file: sassFile,
    //includePaths: ['node_modules/sassdash']
  },
  {
    sass: require('sass'),
    describe,
    it,
  }
);
```

But when I try to **test** it with **jest**, i have this **error message** from **test_sass.js**:

```
Can't find stylesheet to import.
      ╷
    1 │ @import 'scss/sassdash';
      │         ^^^^^^^^^^^^^^^
      ╵
      node_modules/sassdash/_index.scss 1:9   
```
Note: all imports from **/src** files are ok, but it beaks on imports from files inside **node_modules**.

I tried to add `includePaths: ['node_modules/sassdash']` sassOption, but it doesn't work too...

Thanks for your help!
