### ISSUE TITLE
Tests aren't retriggered when .scss test file is modified (with jest --watch)

### ISSUE THREAD

**Issue by maximelebreton** [oddbird/true#166]
Hello there!

When I'm using **True** with **Jest** in watch mode (`jest --watch`), if my `test.scss` file is modified, the tests aren't retriggered.

I assume it's because Jest watch only **.js** files and not **.scss** files, but maybe there is a trick to handle this?

Here are my files:

**test.scss**
```scss
$true-terminal-output: true;
@import "true";

@include describe('test describe') {
    @include it('test it') {
        @include assert-equal(my-function('world'), "Hello%20world");
    }
}
```

**test__sass.js**
```js
var path = require('path');
var sassTrue = require('sass-true');

var sassFile = path.join(__dirname, 'test.scss');

sassTrue.runSass(
  {
    file: sassFile,
  },
  {
    describe,
    it,
  }
);
```

Thanks for your help!
