### ISSUE TITLE
Document mixin flow issues when using `error` mixin

### ISSUE THREAD

**Issue by oscarmarcelo** [oddbird/true#174]
I found a kind of edge case, and honestly I don't think that there may be a viable solution without Sass implementing [try/catch](https://github.com/sass/sass/pull/2850) or something similar, but I'm pointing this anyway in case someone finds a solution, since I didn't find anything yet.

Consider the following:

```sass
@use "sass:meta"

=width ($length)
  @if meta.type-of($length) == map
    @error "Maps aren't allowed"

  width: $length


+width((a: 1px))
```

Now if we replace `@error` by True's `+throw.error`:

1. `+throw.error` now `@return`s something to the mixin, allowing it to continue its flow, instead of stopping it.
2. The compilation breaks because Sass doesn't allow maps in CSS output (`Error: <insert-map-here> isn't a valid CSS value.`).

Now lets explore a bit further:

```sass
@use "sass:meta"
@use "sass-true" as *

@function not-color ($value)
  @if meta.type-of($value) == color
    @return error("Not color", null, true)
  @return $value    

=width ($length)
  @if $length == red
    +error("Not red", null, true)
  width: not-color($length)
  min-width: 1px


+describe("Errors")
  +it("Shouldn't accept colors")
    +output
      +width(red)
    +expect
      /* ERROR: */
      /*   Not red */
```

And the result is:

```css
/* Test: Errors */
/*   ASSERT: Shouldn't accept colors   */
/*   OUTPUT   */
.test-output {
  /* ERROR: */
  /*   Not red */
  width: "ERROR: Not color";
  min-width: 1px;
}

/*   END_OUTPUT   */
/*   EXPECTED   */
.test-output {
  /* ERROR: */
  /*   Not red */
}
```

The flow should stop on the first error, but instead it continues the mixin flow, outputting additional content and errors.

Is there something that can be currently done about this?
