### ISSUE TITLE
how did you make expect mixin read from output mixin

### ISSUE THREAD

**Issue by blackPeppper** [oddbird/true#241]
```scss
@include it('Outputs a font size and line height based on keyword') {
  @include assert {
    @include output {
      @include font-size('large');
    }

    @include expect {
      font-size: 2rem;
      line-height: 3rem;
    }
  }
}
```

and compering the value from font size
