### ISSUE TITLE
iit, xit, and before/after blocks

### ISSUE THREAD

**Issue by zhigang1992** [oddbird/true#25]
##### Before After Blockes?

> Not sure how to implement through, we have a `_true-reset`, but there's no way to tape in to that.
##### `iit` and `xit` like feature?

> a dummy `xtest` for `xit`?

**Comment by ericam** [comment]
Before/After Blocks
--------------------------

I assume the before/after blocks would be used for setting/resetting global variables? That may be possible. It would look something like this:

```scss
$foo: bar;
$fip: bing;

@include test-module('setup/teardown') {
  @include setup(foo: baz, fip: flap);

  @include test('sets up new values for global variables') {
    @include assert-equal($foo, baz, '$foo is now baz');
    @include assert-equal($fip, flap, '$fip is now flap');
  }

  @include teardown;

  @include test('returns global variables to initial values') {
    @include assert-equal($foo, bar, '$foo is bar again');
    @include assert-equal($fip, bing, '$fip is bing again');
  }
}
```

We could also accept setup/before arguments in the `test-module` or `test` mixins, and do automatic teardown at the end of the block.

```scss
$foo: bar;
$fip: bing;

@include test-module('setup/teardown', foo: baz, fip: flap) {
  @include test('sets up new values for global variables') {
    @include assert-equal($foo, baz, '$foo is now baz');
    @include assert-equal($fip, flap, '$fip is now flap');
  }
}
```

`iit` and `xit`
----------------

If I understand these right, `iit` allows you to run a single test, and `xit` allows you to skip a test?

Any implementation of `iit` would require a marker at the beginning of your tests, not just on the test itself. That might be possible, but won't be quite as simple an API as adding the letter `i` before a mixin. That's just a limitation of Sass. I'll look into it more.

`xit` is simple, and a great idea.
