### ISSUE TITLE
@include output includes uncompiled sass functions

### ISSUE THREAD

**Issue by floroz** [oddbird/true#253]
When testing a mixin that invokes functions under the hood, those functions are uncompiled in the final output:

Versions: 

```json
    "sass": "^1.58.3",
    "sass-true": "^7.0.0",
```

```scss
@use "./functions" as *;

@mixin font($size, $weight: 300) {
  font-size: rem($size);
  font-weight: $weight;
  letter-spacing: initial;
  line-height: line-height($size);
}
```

```scss
@include describe("font [function]") {
  @include test("font should return the correct value") {
    @include assert {
      @include output {
        @include font(16);
      }

      @include expect {
        font-size: 1rem;
        font-weight: 300;
        letter-spacing: initial;
        line-height: 1.4;
      }
    }
  }
}
```

Console Output:

```sh
+ Received

  .test-output .test {
-   font-size: 1rem;
+   font-size: rem(16);
    font-weight: 300;
    letter-spacing: initial;
-   line-height: 1.4;
+   line-height: line-height(16);
  }
```

<img width="180" alt="Screenshot 2023-04-04 at 12 41 18" src="https://user-images.githubusercontent.com/45793869/229767565-4635d412-a214-498e-bd58-836664aac861.png">
