### ISSUE TITLE
Expand true.contains to support substring matching

### ISSUE THREAD

**Issue by DT3264** [oddbird/true#302]
The current true.contains assertion in the true Sass testing framework requires a full match against the generated CSS output. This can be limiting when testing for the presence of specific values, variables, or partial CSS structures.

This feature request proposes enhancing true.contains to support substring matching. Instead of requiring a complete CSS rule or value, true.contains would check if the provided string is a substring of the generated CSS.

Example Use Case:

```scss
@include true.test('Check for variable presence') {
  @include true.assert {
    @include true.output {
      .my-class {
        property: my-value;
      }
    }
    @include true.contains {
      my-value
    }
  }
}
```

Are there any current workarounds or alternative approaches to achieve this kind of substring matching with true? 
If not, what would be the best way to include this feature?
