### ISSUE TITLE
Media Queries are computed as 'undefined'

### ISSUE THREAD

**Issue by MakhBeth** [oddbird/true#43]
Hello, 
I'm trying to test some media queries and I've some issues about it.

Here an example: 
```scss 
@include test-module('Visibility') {
  @include test('Visibility test') {
    @include assert('') {
      @include input {
        @media screen and (min-width: 480px) {
          display: none;
        }
      }
      @include expect {
        display: none;
      }
    }
  }
};
```

When I run mocha, I receive this output
```"undefined" equal "display: none;"```
