### ISSUE TITLE
problems with call()

### ISSUE THREAD

**Issue by lunelson** [oddbird/true#50]
Not sure where the problem lies, but the following test does not work though it should:

```scss
@function apply($args) { @return call($args...); }

@include test-module('util/function') {

  // apply
  @include test('apply [fn]') {

    $desc: 'applies a function, passing args as splat to call';
    @function foo($a, $b, $c){ @return $a $b $c; }
    $input: apply(foo 1 2 3);
    $expect: 1 2 3;
    @include assert-equal($input, $expect, $desc);

  }
}
```

Using `call()` on its own does work, but not as invoked above. The `apply()` function does work as expected in other use.

**Comment by mirisuzanne** [comment]
I think this is a libsass bug. It passes when I run it in Ruby Sass, and fails in Libsass. @xzyfer, any thoughts? Here's the output:

```css
[data-module="util/function"] [data-test="apply [fn]"] .assert-equal {
  -result: FAIL;
  -description: "applies a function, passing args as splat to call";
  -expected--list: 1 2 3;
  -returned--string: foo 1 2 3...();
}
```
