### ISSUE TITLE
include description of the failed tests

### ISSUE THREAD

**Issue by eoneill** [oddbird/true#6]
Just started using **True** and I'm most impressed!

The one thing I'd like to see (for debugging purposes) is to indicate which test failed.

For example (using 0.2.0.rc.3)...

``` scss
@include test-module('tests') {
  @include test('[function] nth()') {
    $list: (1 2 3);
    // this assertion is correct
    @include assert-equal(nth($list, 1), 1, "1st value should be 1");
    // this assertion is incorrect and should be fixed
    @include assert-equal(nth($list, 2), 1, "2nd value should be 2");
  }
}
```

results in:

``` css
/*  - FAIL: [function] nth() (2 Assertions, 1 Passed, 1 Failed) */
/*  
    1 Tests:
    - 0 Passed
    - 1 Failed */
```

A hint as to which test failed would be incredibly useful. Maybe something like...

``` css
/*  - FAIL: [function] nth() (2 Assertions, 1 Passed, 1 Failed) */
/*    - 2nd value should be 2 */
/*  
    1 Tests:
    - 0 Passed
    - 1 Failed */
...
```

This is especially useful when looking at failures in travis-ci.

Lemme know what you think, happy to put together a pull request for this.
