### ISSUE TITLE
Error when using with grunt "Unexpected rule type "rule"; looking for module header"

### ISSUE THREAD

**Issue by esr360** [oddbird/true#60]
I'm still unsure if this is an error with my code, but I believe I have everything set up correctly.

I'm trying to run tests using Mocha and Grunt, but I'm getting an error. Here is the relevant information generated on the terminal:

```
Running "mochacli:all" (mochacli) task
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/sass/true/_messages.scss:28 DEBUG: 1 Tests, 1 Passed, 0 Failed
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:62
  throw new Error(
  ^

Error: Line 2, column 1: Unexpected rule type "rule"; looking for module header
    at parseError (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:62:9)
    at parseModule (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:83:3)
```

It appears from line 2 as though the tests were run and passed, but I can't figure out why this might be happening.

**Comment by carljm** [comment]
Can you paste the full CSS output from the tests?

**Comment by esr360** [comment]
Thanks for the swift reply. I couldn't actually find a generated CSS file anywhere, but when running the tests manually I get the following output:

```css
/* # Module: breakpoint */
/* -------------------- */
/* Test: should return the appropriate breakpoint value based on the passed key */
/*   ✔  */
/*  */
/*  */
/* # SUMMARY ---------- */
/* 1 Tests: */
/*  - 1 Passed */
/*  - 0 Failed */
/* -------------------- */
```

**Comment by mirisuzanne** [comment]
Can you also paste the `breakpoint`-module tests?

**Comment by esr360** [comment]
Sure:

```scss
@include test-module('breakpoint') {
  @include test('should return the appropriate breakpoint value based on the passed key') {

    $actual   : kgs-breakpoint('break-3');
    $expected : 940px;

    @include assert-equal($actual, $expected);

  }
}
```
