### ISSUE TITLE
Mocha does not terminate

### ISSUE THREAD

**Issue by tristanlins** [oddbird/true#64]
I created a test as described here: https://github.com/oddbird/true#usage

But when I run "mocha" or "npm test", the process does not terminate :-(

```
$ npm test

> metropolis_base@1.0.0 test /home/lins/workspaces/ionas4-styles/metropolis_base
> mocha



  @function optimize-properties()
    ✓ called without breakpoint values
    ✓ called with values for one breakpoint
    ✓ called with values for multiple breakpoints
    ✓ called with values for mixed breakpoints

  @mixin breakpoint-config()
    ✓ generates properties without breakpoints.


  5 passing (8ms)

█ 
```

After the "5 passing" the cursor blinks and mocha does not terminate.
Not sure if this is a mocha or true issue?!

-----

Here are my test sources:

`package.json`

```json
{
  "devDependencies": {
    "mocha": "^2.5.3",
    "node-sass": "^3.8.0",
    "sass-true": "^2.1.2",
  },
  "scripts": {
    "test": "mocha"
  },
}
```

`test/test_sass.js`

```js
var path = require('path');
var winston = require('winston');
var sassTrue = require('sass-true');
var importer = require('./importer.js');

winston.level = "info";

sassTrue.runSass({
	file: path.join(__dirname, "test_sass.scss"),
	importer: importer
}, describe, it);
```

`test/test_sass.scss`

```scss
// Mocha test-lib
@import "../node_modules/sass-true/sass/true";

// Sources
@import "../css/initial";
@import "../node_modules/foundation-sites/scss/global";
@import "../css/style";

// Tests
@import "functions/optimize-properties-test";
@import "mixins/breakpoint-config-test";
```

`test/functions/_optimize-properties-test.scss`
```scss
@include test-module("@function optimize-properties()") {
  @include test("called without breakpoint values") {
    $actual: optimize-properties(( ... ));

    $expected: ( ... );

    @include assert-equal($actual, $expected, "foo");
  }

  @include test("called with values for one breakpoint") {
    $actual: optimize-properties(( ... ));

    $expected: ( ... );

    @include assert-equal($actual, $expected, "foo");
  }

  @include test("called with values for multiple breakpoints") {
    $actual: optimize-properties(( ... ));

    $expected: ( ... );

    @include assert-equal($actual, $expected, "foo");
  }

  @include test("called with values for mixed breakpoints") {
    $actual: optimize-properties(( ... ));

    $expected: ( ... );

    @include assert-equal($actual, $expected, "foo");
  }
}
```

`test/functions/_breakpoint-config-test.scss`
```scss
@include test-module('@mixin breakpoint-config()') {
  @include test('generates properties without breakpoints.') {
    @include assert('foo') {
      @include output {
        @include breakpoint-config(( ... ));
      }

      @include expect { ... }
    }
  }
}
```
