### ISSUE TITLE
assertions do not work if mixin uses parent selector

### ISSUE THREAD

**Issue by rousso1** [oddbird/true#65]
when using a parent selector in a mixin, the test explode without a reason.
getting "Warning: Can't understand selector"

 e.g: 

``` scss
@mixin change-selector($class-name) {
  .#{$class-name} & {
    @content;
  }
}

@include assert('expect class to be appended to the beginning of the selector') {
  @include input {
    .root {
      .child {
        color: red;

        @include change-selector(special) {
          color: yellow;
        }
      }
    }
  }

  @include expect {
    .root .child {
      color: red;
    }
    .special .root .child {
      color: yellow;
    }
  }
}


```

**Comment by mirisuzanne** [comment]
Yes, that was a known issue, and was noted in the documentation: http://oddbird.net/true/

But it should be fixed in the latest version. What version are you on?

**Comment by rousso1** [comment]
2.0.3

**Comment by mirisuzanne** [comment]
Try upgrading to 2.1.2

**Comment by blackfalcon** [comment]
I am on v5.0.0 and it appears that the issue has returned. 

For example, the following Sass code in my project  ...

```scss
:host(:not(.is-touching)) & {
  &:hover {
    border-width: 0 0 2px 0;
    text-decoration: none;
    cursor: pointer;

    color: $hover-color;
    border-color: currentColor;
  }
}
```

When used in context will output the following CSS ...

```css
:host(:not(.is-touching)) .hyperlink--tab:hover {
  border-width: 0 0 2px 0;
  text-decoration: none;
  cursor: pointer;
  color: #176cff;
  border-color: currentColor;
}
```

The True output appears to be the following ...

```css
:host(:not(.is-touching)) .test-output .hyperlink--tab:hover {
  border-width: 0 0 2px 0;
  text-decoration: none;
  cursor: pointer;
  color: #054687;
  border-color: currentColor;
}
```

This issue causes any mixin with a parent selector `&` to fail the True test.
