### ISSUE TITLE
Percent !+ percent

### ISSUE THREAD

**Issue by samusgray** [oddbird/true#7]
Hi Eric, 

I really enjoy using True. Thanks for making it rock. 

It's possible that I'm testing this Sass mixin wrong, but it doesn't seem to do what I expect when asserting equivalence between two integer percentages. 
## Function to test:

``` css
// Return the total space occupied by multiple columns and associated gutters.
// Useful for adding padding or margins (prefix, suffix, push, pull, etc.)
//
//  $columns  : The number of columns to get relative space for.
//  $context  : The grid context in columns, if nested.
//  $style    : The container style to use.
@function space(
  $columns,
  $context  : $total-columns,
  $style    : fix-static-misalignment()
) {
  @return columns($columns, $context, $style) + if($columns >= 1, gutter($context, $style), 0);
}
```
## True test

``` css
  @include test("space") {
    $test: space(12, 24);
    $expect: 50.42017%;
    @include assert-equal($test, $expect,
      "Returns correct layout based on min width."
    );
  }  
```
## Terminal output from 'compass watch'

```
WARNING: space: Returns correct layout based on min width. (Expected: 50.42017% != Result: 50.42017%)
```

I've tried adding single and double quotes around the value "50.42017%". I've tried dropping the %, etc. It still claims that 50.42017% != 50.42017%.

Am I doing something wrong or should we investigate this issue further in True?
