### ISSUE TITLE
Test failure when output and expected match

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#84]
```
28 DEBUG: function: opposite-direction » it should output a color thats is a percentage lighter when given a color
28 DEBUG: - Output [list]: (bottom,)
28 DEBUG: - Expected [list]: (bottom,)
WARNING: FAILED [assert-equal]: Return the opposite direction
Backtrace:
	node_modules/sass-true/sass/true/_messages.scss:32, in mixin `-true-message`
	node_modules/sass-true/sass/true/_assert.scss:201, in mixin `-true-assert-results`
	node_modules/sass-true/sass/true/_assert.scss:61, in mixin `assert-equal`
	src/styles/functions/tests/_opposite-direction.scss:12, in mixin `@content`
	node_modules/sass-true/sass/true/_tests.scss:16, in mixin `test`
	src/styles/functions/tests/_opposite-direction.scss:8, in mixin `@content`
	node_modules/sass-true/sass/true/_modules.scss:15, in mixin `test-module`
	src/styles/functions/tests/_opposite-direction.scss:6
```

Running a test on a function and getting this error when it appears to get the expected

```scss
@import "true";
@import "../opposite-direction";

@include test-module("function: opposite-direction") {

	@include test("it should output the opposite direction when given input") {
		$test: opposite-direction(top);
		$expected: (bottom,);

		@include assert-equal($test, $expected, "Return the opposite direction");
	}
}
```

**Comment by mirisuzanne** [comment]
Yeah, Sass is a little weird about list comparisons. If you can paste the `opposite-direction` function, I can figure out better what's going on, and why it thinks these are different.

**Comment by chrisopedia** [comment]
```scss
// Returns the opposite direction of each direction in a list
// @author Hugo Giraudel
// @param {List} $directions - List of initial directions
// @return {List} - List of opposite directions
// sass-lint:disable property-sort-order
@function opposite-direction($directions) {
	$opposite-directions: ();
	$direction-map: (
		"top": "bottom",
		"right": "left",
		"bottom": "top",
		"left": "right",
		"center": "center",
		"topleft": "top",
		"topright": "top",
		"bottomleft": "bottom",
		"bottomright": "bottom",
		"ltr": "rtl",
		"rtl": "ltr"
	);

	@each $direction in $directions {
		$direction: to-lower-case($direction);

		@if map-has-key($direction-map, $direction) {
			$opposite-directions: append($opposite-directions, unquote(map-get($direction-map, $direction)));
		} @else {
			@warn "No opposite direction can be found for `#{$direction}`. Direction omitted.";
		}
	}

	@return $opposite-directions;
}
```

**Comment by chrisopedia** [comment]
I got it to work but this was what I had to do:

```
	@include test("it should return bottom when given top") {
		$test: inspect(opposite-direction("top"));
		$expected: inspect((bottom,));

		@include assert-equal($test, $expected, "Return the opposite direction");
	}
```

**Comment by mirisuzanne** [comment]
I still get `false` when I inspect them, probably because one is comma-delimited and the other is space-delimited? I've been playing around with [this demo on Sassmeister](http://www.sassmeister.com/gist/f613227686b3792e0c3ccb227f16a4f6), but can't figure out the right solution.

**Comment by mirisuzanne** [comment]
The workaround that makes more sense to me is `$expected: append((), bottom);` — which is the same construction technique used in your function.

**Comment by mirisuzanne** [comment]
@chriseppstein Thoughts on how we should handle this type of comparison?

**Comment by chrisopedia** [comment]
FYI, i switched to your work around and it works just fine.  Thanks.

**Comment by chrisopedia** [comment]
@mirisuzanne ran into another issue:

```
  1 failing

  1) function: scale-luminance it should change the color to have the required luminance:

      AssertionError: Return the correct color ("[color] #00c4d3" assert-equal "[color] #00c4d3")
      + expected - actual


      at node_modules/sass-true/lib/main.js:59:20
      at Function._.each._.forEach (node_modules/sass-true/node_modules/underscore/underscore.js:153:9)
      at Context.<anonymous> (node_modules/sass-true/lib/main.js:50:11)```

**Comment by mirisuzanne** [comment]
@chrisopedia wow, that's even more of a stumper. Can you paste the function for me to experiment with?

**Comment by chrisopedia** [comment]
its a lot to paste in here and there are a lot of deps, so I created this [gist](https://gist.github.com/chrisopedia/e7c4ed50ddae2565949e5e5e8b97767e) for you.  The `deps.scss` are just a bunch of math functions used for the `scale-luminense.scss`

**Comment by mirisuzanne** [comment]
Thanks! What's the test look like?

**Comment by chrisopedia** [comment]
```
@include test-module("function: scale-luminance") {

	@include test("it should change the color to have the required luminance") {
		$test: scale-luminance(rgb(0, 173, 187), .44042);
		$expected: #00c4d3;

		@include assert-equal($test, $expected, 'Return the correct color');
	}
}
```

**Comment by mirisuzanne** [comment]
Interesting. That's passing for me on Sassmeister, though they are on an old version of True (2.0.3)...

https://www.sassmeister.com/gist/84acddb3a9358a60335e8b3666103945

I'll try it out locally.

**Comment by mirisuzanne** [comment]
Locally I get a different result from the function. Curiouser and curiouser...

Using Sass `3.4.6` and True `2.2.2`:

```
/* # Module: function: scale-luminance */
/* ------------------------------------- */
/* Test: it should change the color to have the required luminance */
/*   ✖ FAILED [assert-equal]: Return the correct color */
/*     - Output [color]: #00c3d3 */
/*     - Expected [color]: #00c4d3 */
```

When I change the expected color to `#00c3d3` it passes.

Looks like Sassmeister is using Sass `3.4.21` - was there a change in Sass color-handling?

Either way, I'm not able to replicate your same-color-fail yet.

**Comment by chrisopedia** [comment]
I'm on Ruby Sass `3.4.23 (Selective Steve)` and True `2.2.2`

**Comment by mirisuzanne** [comment]
Looks like Sass did make changes to rounding in recent bug-fixes. That could explain the different results. Still, I can' recreate your error. With Ruby Sass 3.4.23 and True 2.2.2 I get a passing result:

```
/* # Module: function: scale-luminance */
/* ------------------------------------- */
/* Test: it should change the color to have the required luminance */
/*   ✔ Return the correct color */
```

**Comment by chrisopedia** [comment]
How are you running it?  I'm using this in Gulp task using Mocha.

**Comment by mirisuzanne** [comment]
I'm compiling directly in Sass. Since mocha trusts the Sass results, it would be very strange if that gulp/mocha explains the error. Can you paste your relevant gulp setup, for me to try it locally here?

**Comment by chrisopedia** [comment]
// True Sass True task; runs unit tests on mixins/functions
const mocha = require('gulp-mocha');
```javascript
module.exports = (gulp, input) => {
	gulp.task('sass-true', () =>
		gulp.src(input, {
			read: false
		})
		.pipe(mocha({
			reporter: 'mochawesome',
			reporterOptions: {
				reportDir: '.mochawesome',
				reportFilename: 'sass-true'
			}
		}))
	);
};```

**Comment by mirisuzanne** [comment]
Ok, I finally got this all working, and I see the same error you do. Very strange! I'll see if I can figure anything out. @carljm might have some better insight into the differences here?

**Comment by mirisuzanne** [comment]
Looks like `inspect` does resolve most of our issues:

```
@function _true-is-equal($one, $two) {
  @if type-of($one) == type-of($two) {
    @return inspect($one) == inspect($two);
  }

  @return false;
}
```

That doesn't solve the list-comparison, where single-item lists are still required to have the same delimiter (space or comma). Your demo to start this thread creates a space-delimited (default) list in the function, but you are expecting a comma-delimited list.

There's a simple solution, which is to force single-item (or empty) lists into the same delimiter before comparing. 

```
@function _true-is-equal($one, $two) {
  $type-one: type-of($one);
  $type-two: type-of($two);

  @if $type-one == $type-two {
    // force short lists to use the same separator
    @if ($type-one == 'list') {
      $one: if(length($one) < 2, join((), $one, space), $one);
      $two: if(length($two) < 2, join((), $two, space), $two);
    }

    @return inspect($one) == inspect($two);
  }

  @return false;
}
```

That comes with a trade-off: if you ever want to test that your lists have different delimiters, you would need to create multiple-item lists for that test. That seems like a worthwhile sacrifice, I think?

I keep trying to find the balance between comparing what Sass sees internally, and what users actually need to know. The farther we get from the Sass understanding, the more leaky our abstraction becomes. Again, I think it's worth it?

**Comment by mirisuzanne** [comment]
I am still checking that both variable-type and inspected-value match, because I think it's important to understand that `"1em"` and `1em` are functionally different.

**Comment by chrisopedia** [comment]
Why do you suggest they're functionally different?

**Comment by mirisuzanne** [comment]
CSS doesn't care about the difference, but True is often testing internal values for Sass toolkits - where the difference between a number and a string of that number can grind your compiler to a halt. `1em + 1em == 2em` while `"1em" + "1em" == "1em1em"`.

**Comment by chrisopedia** [comment]
Ahh, thanks for the insight.  So then after all of this discussion, whats your best recommendation to get these tests passing for where [this](https://github.com/oddbird/true/issues/84#issuecomment-298091823) keeps happening.

**Comment by mirisuzanne** [comment]
It seems to be related to color-math rounding. The two aren't equal, because the version of Sass you are using (actually node-sass, since that is the only option with gulp/mocha) isn't rounding before it compares values. You can fix that with `inspect()` around the result.

**Comment by chrisopedia** [comment]
thanks, that fixed it.

**Comment by chrisopedia** [comment]
@mirisuzanne hate to bother you again, but wondering if this is the same issue with comparisons:

```
@include test-module("mixin: label-variant") {

	@include test("it should output style for a label when given a color") {

		@include assert() {

			@include output {
				@include label-variant($black);
			}

			@include expect {
				background-color: $black;

				&[href],
				> .close {
					@include hover-focus {
						background-color: tint($black, 30%);
					}
				}

				> .close {
					&:focus,
					&.focus,
					&:active,
					&.active {
						background-color: shade($black, 30%);
					}

					&.disabled,
					&:disabled,
					[disabled] {
						@include hover {
							background-color: transparent;
						}
					}
				}
			}
		}
	}
}
```

**Comment by mirisuzanne** [comment]
I'm not sure what issue you are having there? CSS-output tests should already be comparing the final values in the CSS, so I doubt it's the same problem - but hard to tell at this point.

**Comment by chrisopedia** [comment]
```
     AssertionError:  (".test-output {
  background-color: black;
}

.test-output > .label-pill {
  background-color: shade(black, 30%);
}

.test-output[href]:focus,
.test-output[href]:hover,
.test-output > .close:focus,
.test-output > .close:hover {
  background-color: tint(black, 30%);
}

.test-output > .close:focus,
.test-output > .close.focus,
.test-output > .close:active,
.test-output > .close.active {
  background-color: shade(black, 30%);
}

.test-output > .close.disabled:hover,
.test-output > .close:disabled:hover,
.test-output > .close [disabled]:hover {
  background-color: transparent;
}" equal ".test-output {
  background-color: black;
}

.test-output[href]:focus,
.test-output[href]:hover,
.test-output > .close:focus,
.test-output > .close:hover {
  background-color: tint(black, 30%);
}

.test-output > .close:focus,
.test-output > .close.focus,
.test-output > .close:active,
.test-output > .close.active {
  background-color: shade(black, 30%);
}

.test-output > .close.disabled:hover,
.test-output > .close:disabled:hover,
.test-output > .close [disabled]:hover {
  background-color: transparent;
}")
      + expected - actual

       .test-output {
         background-color: black;
       }

      -.test-output > .label-pill {
      -  background-color: shade(black, 30%);
      -}
      -
       .test-output[href]:focus,
       .test-output[href]:hover,
       .test-output > .close:focus,
       .test-output > .close:hover {

      at node_modules/sass-true/lib/main.js:59:20
      at Function._.each._.forEach (node_modules/sass-true/node_modules/underscore/underscore.js:153:9)
      at Context.<anonymous> (node_modules/sass-true/lib/main.js:50:11)```

Sorry, heres the error.

**Comment by mirisuzanne** [comment]
Those two blocks aren't actually the same. You're missing...

```scss
.test-output > .label-pill {
  background-color: shade(black, 30%);
}
```

In your `expected` block.
