### ISSUE TITLE
Test if a function throws?

### ISSUE THREAD

**Issue by lazarljubenovic** [oddbird/true#92]
It would be really nice to add ability to test if a function throws (like `expect(...).toThrow('error message')`.

**Comment by mirisuzanne** [comment]
I agree. Here's [how we did it in Susy](https://github.com/oddbird/susy/commit/de0c473a95d99117475f1c023f17423803bb7e7b). I don't feel like I can ship that as part of True, because it adds a function to your production code. I don't want True to be a production dependency, so it's better if that function lives outside True.

Add a variable and function like these to your project:

```scss
$_test-environment: false;

@function _error(
  $message,
  $capture: $_test-environment
) {
  @if $capture {
    @return 'ERROR: #{$message}';
  }

  @error '#{$message}';
}
```

Return that function wherever you would normally `@error`:

```scss
// what you had before...
@error "that won't work at all, please try again";

// what you use now...
@return _error("that won't work at all, please try again");
```

In your production code, set `$_test-environment: false;` and then change it to `true` in your testing environment. Suddenly failing functions will return error messages you can test for:

```scss
  @include test('Error on invalid thing') {
    @include assert-equal(
      my-function(3),
      'ERROR: that won't work at all, please try again');
  }
```

Does that make sense? If you have ideas for a better way to do that without adding production requirements, I'm all ears!
